# -*- coding: utf-8 -*-

"""""""""""""""""""""""""""""""""""""""""""""""""""
"""""""""""""""""""""""""""""""""""""""""""""""""""
#Constantes de la interfaz

POSICION_SUS_ACCIONES = 0
POSICION_SUS_MARCADORES = 1
POSICION_GUERRERAS = 2
POSICION_MIS_MARCADORES = 3
POSICION_MIS_ACCIONES = 4
POSICION_MI_MANO = 5
POSICION_ACCION = 6
POSICION_ACEPTAR = 7

#CARTA_ENORME_ALTO = 220
#CARTA_ENORME_ANCHO = 150

CARTA_GRANDE_ALTO = 145
CARTA_GRANDE_ANCHO = 100

CARTA_PEQUE_ALTO = 110
CARTA_PEQUE_ANCHO = 75

CARTA_ACCION_LADO = 110

BOTON_ALTO = 1
BOTON_ANCHO = 2

BORDE_NULO = 0
BORDE_CLICKABLE = 1
BORDE_MARCADO = 2

PADDING = 2

VENTANA_ALTO=730
VENTANA_ANCHO= 810

#Textos de las acciones
TEXTO_ACCION_SECRETO = "Secreto"
TEXTO_ACCION_RENUNCIA = "Renuncia"
TEXTO_ACCION_REGALO = "Regalo"
TEXTO_ACCION_COMPETICION = "Competición"
TEXTO_PENDIENTE_REGALO = "Elija una carta entre\nlas siguientes 3"
TEXTO_PENDIENTE_COMPETICION = "Elija entre\nlas 2 primeras cartas\no las 2 ultimas"
